SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

CREATE TABLE public.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login text NOT NULL UNIQUE,
    full_name text,
    email text,
    role text NOT NULL,
    password_hash text NOT NULL,
    salt text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    active boolean DEFAULT true
);

CREATE TABLE public.disciplines (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    code text UNIQUE
);

CREATE TABLE public.assignments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    discipline_id integer REFERENCES public.disciplines(id) ON DELETE SET NULL,
    created_by integer REFERENCES public.users(id) ON DELETE SET NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    due_date timestamp without time zone
);

CREATE INDEX idx_assignments_created_by ON public.assignments (created_by);

CREATE TABLE public.submissions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id integer REFERENCES public.assignments(id) ON DELETE CASCADE,
    student_id integer REFERENCES public.users(id) ON DELETE SET NULL,
    file_path text NOT NULL,
    original_name text NOT NULL,
    uploaded_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    grade text,
    feedback text
);

CREATE INDEX idx_submissions_assignment ON public.submissions (assignment_id);
CREATE INDEX idx_submissions_student ON public.submissions (student_id);

CREATE TABLE public.assignment_files (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id integer NOT NULL REFERENCES public.assignments(id) ON DELETE CASCADE,
    file_path text NOT NULL,
    original_name text NOT NULL,
    uploaded_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_assignment_files_assignment ON public.assignment_files (assignment_id);

CREATE TABLE public.audit_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer REFERENCES public.users(id) ON DELETE SET NULL,
    action text,
    details text,
    ts timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.assignment_students (
    assignment_id integer NOT NULL REFERENCES public.assignments(id) ON DELETE CASCADE,
    student_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    PRIMARY KEY (assignment_id, student_id)
);
